### PR TITLE
add missing FILENAMES argument to `all-repos-grep`

### PR DESCRIPTION
**Pull request by jugmac00**
cf documentation for `all-repos-sed`.

### CODE REVIEW

**Comment by asottile** [comment]
filenames is not required for all-repos-grep

**Comment by jugmac00** [comment]
At least it is optional... which is not obvious from reading the current documentation.

**Comment by asottile** [comment]
see `git grep --help` ?

**Comment by jugmac00** [comment]
Oh my - thanks!

**Pull request closed without merging**
