### PR TITLE
autofixer: Support custom branch prefix

### PR DESCRIPTION
**Pull request by KindDragon**
Our policies only allow branches with certain prefixes

### CODE REVIEW

**Comment by asottile** [comment]
no thanks, it's meant as a subtle nudge towards the tool

**Comment by asottile** [comment]
please discuss new features before spending time on them thanks!

**Comment by KindDragon** [comment]
I mean, we can't use it without this feature with our GitLab repositories.
We have several dozen repositories configured manually to use a branch prefix ('feature/' or 'fix/') (GitLab has no built-in tool to change settings for multiple repositories). Therefore, this functionality has been implemented.

**Comment by asottile** [comment]
you can, it's just intentionally not easy -- you'll have to adjust or wrap the `push` plugins to implement your behaviour to adjust to your (imo unnecessarily restrictive) branch convention

**Comment by faph** [comment]
@KindDragon This suggestion was similarly rejected here: https://github.com/asottile/all-repos/issues/158 😞

**Pull request closed without merging**
